import './command';
import './config';
import './index';
import './text';
import './loadCommands';
import './registerCommands';
import './updateNotifier';
import './version';
import './CommandHelper';
