// import './allCommands';
// import './command';
// import './CommandHelper';
// import './configurationHelper';
// import './config';
// import './index';
// import './installableCommands';
// import './loadCommands';
// import './npmInstall';
// import './registerCommands';
// import './text';
// import './template';
// import './updateNotifier';
// import './commands/eject';
// import './commands/init';
import './commands/version';
// import './bin/dojo';
